//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class official_inf
    {
        public int idEmployee { get; set; }
        public Nullable<int> personalNum { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public Nullable<int> idDep { get; set; }
        public Nullable<int> idPost { get; set; }
        public string education { get; set; }
        public Nullable<int> idSpec { get; set; }
        public string experience { get; set; }
        public string phoneNum { get; set; }
        public Nullable<int> wage { get; set; }
        public string status { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual posts posts { get; set; }
        public virtual specialty specialty { get; set; }
        public virtual personal_inf personal_inf { get; set; }
    }
}
