//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_inf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personal_inf()
        {
            this.official_inf = new HashSet<official_inf>();
        }
    
        public int personalNum { get; set; }
        public string placeBirth { get; set; }
        public string passport { get; set; }
        public string address { get; set; }
        public string regAddress { get; set; }
        public string maritalStat { get; set; }
        public Nullable<int> children { get; set; }
        public string dateBirth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<official_inf> official_inf { get; set; }
    }
}
