--1.	таблица Report
create table Report
(
    id NUMBER GENERATED by default on null as IDENTITY,
    xm XMLTYPE
);
select * from Report

-- 2.	процедуру генерации XML
create or replace function gXML1
return xmltype 
as
  xml xmltype;
  b nvarchar2(600);
begin
  b:='select systimestamp, personal_inf.passport, departments.department from official_inf 
  inner join personal_inf on official_inf.personalNum=personal_inf.personalNum
  inner join departments on departments.idDep=official_inf.idDep';

  dbms_output.put_line(b);
        
  select xmlelement("XML", xmlelement(evalname('official_inf'), dbms_xmlgen.getxmltype( b ))) into xml from dual;
  return xml;
end gXML1;

set serveroutput on
select (gXML1).getstringval() from dual;

---- 3.	вставки  XML 
CREATE OR REPLACE PROCEDURE InsXML(
    idx integer,
    x IN XMLTYPE)
IS
BEGIN
  INSERT INTO Report (id, xm) 
  VALUES (idx, x);
  COMMIT;
END;

begin
InsXML(2, gXML1);
end;

select * from Report;
select r.xm.GETSTRINGVAL() from Report r;

--4.	 индекс над XML-столбцом 
create index xmlInd on Report(extractvalue(xm, '/XML/official_inf/ROW/ID[0]/text()'));

--5. Извлечения 
--drop procedure FindXML
 select t.xm.extract('/XML/official_inf/ROWSET/ROW').GETSTRINGVAL() from Report t;
 
 drop function gXML1
 drop PROCEDURE InsXML
 drop  table Report